---
name: Run Tests

'on':
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: interactivetextanalyzer/package-lock.json

      - name: Install dependencies
        working-directory: interactivetextanalyzer
        run: npm ci

      - name: Run tests
        working-directory: interactivetextanalyzer
        run: npm run test:run
